program: |

    fn main() : int {
      baz[5] = 28;
      return 0;
    }
    
    fn baz(a: int) {
      
    }
    
expect_compile_failure: true
expect_stderr: |
  3:3 Type error: Usage of function 'baz' as a variable
    baz[5] = 28;
    ^^^
  7:4 Note: Function declared here:
  fn baz(a: int) {
     ^^^
  Terminating compilation due to 1 error